### ISSUE TITLE
bug detected: when description of stock contains a comma, split works wrong

### ISSUE THREAD

**Issue by geertn444** [nonfiction/nterchange3-extras#1]
First, thanks for the great module yahoo stock module.

I detected a bug in class.yahoostock.php
 when the description of a stock contains a comma, like SWKS stock.
Return for SWKS is:

SWKS,"Skyworks Solutions, Inc.",88.96,"8/5/2015","03:59pm","+0.30%",500

Notice the ',' before  Inc. 
This leads to a wrong split and wrong field values are returned.

**Comment by geertn444** [comment]
Here is a very concise example for a quote aware explode - substrings in quotes (or another definable enclosure char) are not exploded.
An additional parameter allows to determine whether the enclosure chars should be preserved within the resulting array elements. Please note that as of PHP 5.3 the str_getcsv function offers a built-in way to do this!

<?php
function csv_explode($delim=',', $str, $enclose='"', $preserve=false){
  $resArr = array();
  $n = 0;
  $expEncArr = explode($enclose, $str);
  foreach($expEncArr as $EncItem){
    if($n++%2){
      array_push($resArr, array_pop($resArr) . ($preserve?$enclose:'') . $EncItem.($preserve?$enclose:''));
    }else{
      $expDelArr = explode($delim, $EncItem);
      array_push($resArr, array_pop($resArr) . array_shift($expDelArr));
      $resArr = array_merge($resArr, $expDelArr);
    }
  }
  return $resArr;
}
?>

**Comment by andyvanee** [comment]
Thanks for the feedback! To be honest, the modules in this repository are mostly un-maintained. Our current development practices are to rely more on composer packages rather than this collection. 

The source for this is here: https://github.com/nonfiction/nterchange3-extras/blob/master/yahoo-stockquote/lib/class.yahoostock.php. I believe Line 67 in particular is causing your bug. If you'd like to send a pull request, I'd be happy to review and merge.

I would also recommend looking into composer/packagist, as it is generally a better workflow. This package may provide similar functionality, though I haven't tested it: https://packagist.org/packages/scheb/yahoo-finance-api

Thanks again!
